// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef main_h
#define main_h
#include <FL/Fl.H>
void bt_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window_main;
#include <FL/Fl_Button.H>
extern Fl_Button *btnRefreshTime;
#include <FL/Fl_Input.H>
extern Fl_Input *serverTimeOutput;
extern Fl_Input *sysTimeOutput;
extern Fl_Button *btnSyncTime;
#endif
